klibc: Do not let clang generate wcslen builtin
clang-21 decides to emit wcslen call on arm architecture
klibc does not provide widechar support so it should not
be used.

Fixes
| arm-yoe-linux-gnueabi-ld.bfd: usr/kinit/do_mounts_md.o: in function `md_run':
| /usr/src/debug/klibc/2.0.14/usr/kinit/do_mounts_md.c:294:(.text+0x5d6): undefined reference to `wcslen'

Signed-off-by: Khem Raj <raj.khem@gmail.com>